apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: my-coupon-issuer-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-coupon-issuer
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: my-coupon-issuer
    spec:
      containers:
        - name: my-coupon-issuer
          image: jtoh0227/my-coupon-issuer:latest
          ports:
            - containerPort: 8080
              hostPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-coupon-issuer-service
spec:
  selector:
    app: my-coupon-issuer
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-coupon-issuer-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-coupon-issuer-service
                port:
                  number: 8080
#  defaultBackend:
#    service:
#      name: my-coupon-issuer-service
#      port:
#        number: 8080